// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngivzofqryxxwvlxxsqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naXZ6b2Zxcnl4eHd2bHh4c3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzUzOTksImV4cCI6MjA2NzcxMTM5OX0.bqUejSYK88neXuk4SuaCvyVJ7E6k4qLz7rtDOayFquo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});